name: Deploy para S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Verificar arquivos do repositório
        run: ls -la

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Verificar se a pasta pública existe antes do upload
        run: ls -la public || echo "A pasta 'public/' não foi encontrada!"

      - name: Fazer upload para o S3
        run: |
          if [ -d "public" ]; then
            echo "Pasta 'public/' encontrada. Iniciando upload..."
            aws s3 sync public s3://${{ secrets.AWS_S3_BUCKET }} --delete
          else
            echo "Erro: A pasta 'public/' não existe. Verifique o processo de build ou se os arquivos foram commitados no repositório."
            exit 1
          fi
