name: Deploy para S3

on:
  push:
    branches:
      - main  # O deploy será acionado quando houver push na branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Verificar estrutura do projeto
        run: ls -la

      - name: Criar pasta public se não existir
        run: mkdir -p public && cp -r index.html styles.css script.js imagens posts public/

      - name: Verificar arquivos na pasta public
        run: ls -la public

      - name: Fazer upload para o S3
        run: aws s3 sync public s3://${{ secrets.AWS_S3_BUCKET }} --delete
