name: Deploy para S3

on:
  push:
    branches:
      - main  # O deploy será acionado quando houver push na branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Upload dos arquivos para o GitHub Actions
        uses: actions/upload-artifact@v4
        with:
          name: public-folder
          path: public  # Certifique-se de que a pasta 'public' existe

      - name: Baixar os arquivos no runner
        uses: actions/download-artifact@v4
        with:
          name: public-folder

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Fazer upload para o S3
        run: |
          aws s3 sync public s3://${{ secrets.AWS_S3_BUCKET }} --delete
