name: Deploy para AWS S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Substitua pela sua região

      - name: Criar pasta pública e copiar arquivos
        run: |
          mkdir -p public
          cp -r index.html styles.css script.js public/
          [ -d imagens ] && cp -r imagens public/ || echo "Pasta 'imagens' não encontrada"
          [ -d posts ] && cp -r posts public/ || echo "Pasta 'posts' não encontrada"

      - name: Fazer upload para o S3
        run: |
          aws s3 sync public s3://${{ secrets.AWS_S3_BUCKET }} --acl public-read --delete

      - name: Invalidar cache no CloudFront (opcional)
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
        continue-on-error: true
