name: Deploy para S3

on:
  push:
    branches:
      - main  # O deploy será acionado quando houver push na branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

    
